### ISSUE TITLE
When I try to run it on Lambdatest I got this error

### ISSUE THREAD

**Issue by shanehu13** [LambdaTest/taiko-lambdatest#6]
```
PS C:\Automate\ELCAuto\template-js> gauge run ./specs/demo.spec
Trace: TypeError: registerHooks is not a function
at init (C:\Automate\ELCAuto\template-js\node_modules\taiko-lambdatest\index.js:18:3)
at loadPlugin (C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3097:7)
at C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3118:3
at Array.forEach (<anonymous>)
at Object.<anonymous> (C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3107:14)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at loadPlugin (C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3101:13)
at C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3118:3
at Array.forEach (<anonymous>)
at Object.<anonymous> (C:\Automate\ELCAuto\template-js\node_modules\taiko\lib\taiko.js:3107:14)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)

  Error Message: error reading from server: read tcp 127.0.0.1:51784->127.0.0.1:51783: wsarecv: An existing connection was forcibly closed by the remote host.
  Stacktrace:


  Error Message: Runner is not Alive
  Stacktrace:

Successfully generated html-report to => C:\Automate\ELCAuto\template-js\reports\html-report\index.html

Failed to kill Runner: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:51783: connectex: No connection could be made because the target machine actively refused it."
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 1.169s
```
Any ideas about this?Thanks

**Comment by Shivanshu-lambdatest** [comment]
Hi @husheng-kooboo Thanks for opening this Issue. Can you please share more details about how you got this error, the steps etc.

**Comment by ankur-lt** [comment]
Hi @shanehu13, can you also add the code snippet for which is throwing the above error?
As you are using gauge runner, you can refer the sample repository here: https://github.com/LambdaTest/lambdatest-taiko-sample/tree/main/taiko-gauge to run your tests with taiko.

**Comment by 4DvAnCeBoY** [comment]
Closing Due to Inactivity
